name: Push to Another Repo

on:
  push:
    branches:
      - master  # Change this to the branch you want to trigger the workflow on

jobs:
  push_to_another_repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v2
        with:
          repository: https://github.com/Naveenmorty/SampleWar.git
          ref: master

      - name: Configure Git
        run: |
          git config user.name "${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_4A6CF52EEFA54D97802FDAB3E9CC0E95 }}"
          git config user.email "${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_4A6CF52EEFA54D97802FDAB3E9CC0E95 }}@Naveenmorty.noreply.github.com"

      - name: Push to destination repository
        run: |
          git remote add destination_repo https://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@github.com/Changepond-DevOps/github-hook.git
          git push destination_repo main  # Replace with the branch you want to push

